version: '3'

services:
  amorer_db:
    image: mysql:8.0
    hostname: amorer_db
    ports:
      - "33306:3306"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_ja_0900_as_cs
  amorer_web:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: amorer_rails_web
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    links:
      - amorer_db
    command: bundle exec rails server -b 0.0.0.0
